POST http://localhost:3000/createBook
Content-Type: application/json

{ 
    "text": "HAHAHA", 
    "title": "he", 
    "author": "HAHAHA", 
    "imageUrl": "", 
    "publisher": "HAHAHA"
}

###

GET http://localhost:3000/chapters
###

GET http://localhost:3000/chapter
Content-Type: application/json

{
    "url": "https://www.uukanshu.com/b/439/374747.html"
}